// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"api_service/pkg/apiclient/v1/entity"
)

// NewPostSignUpParams creates a new PostSignUpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostSignUpParams() *PostSignUpParams {
	return &PostSignUpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostSignUpParamsWithTimeout creates a new PostSignUpParams object
// with the ability to set a timeout on a request.
func NewPostSignUpParamsWithTimeout(timeout time.Duration) *PostSignUpParams {
	return &PostSignUpParams{
		timeout: timeout,
	}
}

// NewPostSignUpParamsWithContext creates a new PostSignUpParams object
// with the ability to set a context for a request.
func NewPostSignUpParamsWithContext(ctx context.Context) *PostSignUpParams {
	return &PostSignUpParams{
		Context: ctx,
	}
}

// NewPostSignUpParamsWithHTTPClient creates a new PostSignUpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostSignUpParamsWithHTTPClient(client *http.Client) *PostSignUpParams {
	return &PostSignUpParams{
		HTTPClient: client,
	}
}

/*
PostSignUpParams contains all the parameters to send to the API endpoint

	for the post sign up operation.

	Typically these are written to a http.Request.
*/
type PostSignUpParams struct {

	/* SignUpRequest.

	   Запрос на регистрацию пользователя
	*/
	SignUpRequest *entity.EntitySignUpRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post sign up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSignUpParams) WithDefaults() *PostSignUpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post sign up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSignUpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post sign up params
func (o *PostSignUpParams) WithTimeout(timeout time.Duration) *PostSignUpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post sign up params
func (o *PostSignUpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post sign up params
func (o *PostSignUpParams) WithContext(ctx context.Context) *PostSignUpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post sign up params
func (o *PostSignUpParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post sign up params
func (o *PostSignUpParams) WithHTTPClient(client *http.Client) *PostSignUpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post sign up params
func (o *PostSignUpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSignUpRequest adds the signUpRequest to the post sign up params
func (o *PostSignUpParams) WithSignUpRequest(signUpRequest *entity.EntitySignUpRequest) *PostSignUpParams {
	o.SetSignUpRequest(signUpRequest)
	return o
}

// SetSignUpRequest adds the signUpRequest to the post sign up params
func (o *PostSignUpParams) SetSignUpRequest(signUpRequest *entity.EntitySignUpRequest) {
	o.SignUpRequest = signUpRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostSignUpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.SignUpRequest != nil {
		if err := r.SetBodyParam(o.SignUpRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
