// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntitySignUpRequest entity sign up request
//
// swagger:model entity.SignUpRequest
type EntitySignUpRequest struct {

	// email
	Email string `json:"email,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this entity sign up request
func (m *EntitySignUpRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this entity sign up request based on context it is used
func (m *EntitySignUpRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntitySignUpRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntitySignUpRequest) UnmarshalBinary(b []byte) error {
	var res EntitySignUpRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
