// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InfoReader is a Reader for the Info structure.
type InfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewInfoInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /info] info", response, response.Code())
	}
}

// NewInfoOK creates a InfoOK with default headers values
func NewInfoOK() *InfoOK {
	return &InfoOK{}
}

/*
InfoOK describes a response with status code 200, with default header values.

OK
*/
type InfoOK struct {
}

// IsSuccess returns true when this info o k response has a 2xx status code
func (o *InfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this info o k response has a 3xx status code
func (o *InfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this info o k response has a 4xx status code
func (o *InfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this info o k response has a 5xx status code
func (o *InfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this info o k response a status code equal to that given
func (o *InfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the info o k response
func (o *InfoOK) Code() int {
	return 200
}

func (o *InfoOK) Error() string {
	return fmt.Sprintf("[GET /info][%d] infoOK", 200)
}

func (o *InfoOK) String() string {
	return fmt.Sprintf("[GET /info][%d] infoOK", 200)
}

func (o *InfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInfoInternalServerError creates a InfoInternalServerError with default headers values
func NewInfoInternalServerError() *InfoInternalServerError {
	return &InfoInternalServerError{}
}

/*
InfoInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type InfoInternalServerError struct {
}

// IsSuccess returns true when this info internal server error response has a 2xx status code
func (o *InfoInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this info internal server error response has a 3xx status code
func (o *InfoInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this info internal server error response has a 4xx status code
func (o *InfoInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this info internal server error response has a 5xx status code
func (o *InfoInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this info internal server error response a status code equal to that given
func (o *InfoInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the info internal server error response
func (o *InfoInternalServerError) Code() int {
	return 500
}

func (o *InfoInternalServerError) Error() string {
	return fmt.Sprintf("[GET /info][%d] infoInternalServerError", 500)
}

func (o *InfoInternalServerError) String() string {
	return fmt.Sprintf("[GET /info][%d] infoInternalServerError", 500)
}

func (o *InfoInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
